static_sites:
  - type: static
    name: marly-frontend
    env: static
    rootDir: marly-handmade-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: "/"
        destination: "/index.html"
        status: 200
      - type: rewrite
        source: "/*"
        destination: "/index.html"
        status: 200